# Component metadata picked up by Streamlit at runtime.
[project]
name = "st-mui"
version = "0.3.7"

[[tool.streamlit.component.components]]
name = "date_picker"
asset_dir = "date_picker/frontend/build"

[[tool.streamlit.component.components]]
name = "time_picker"
asset_dir = "time_picker/frontend/build"

[[tool.streamlit.component.components]]
name = "date_time_picker"
asset_dir = "date_time_picker/frontend/build"

[[tool.streamlit.component.components]]
name = "date_range_picker"
asset_dir = "date_range_picker/frontend/build"

[[tool.streamlit.component.components]]
name = "date_time_range_picker"
asset_dir = "date_time_range_picker/frontend/build"

[[tool.streamlit.component.components]]
name = "tree_view"
asset_dir = "tree_view/frontend/build"

[[tool.streamlit.component.components]]
name = "autocomplete"
asset_dir = "autocomplete/frontend/build"

[[tool.streamlit.component.components]]
name = "slider"
asset_dir = "slider/frontend/build"

[[tool.streamlit.component.components]]
name = "rating"
asset_dir = "rating/frontend/build"

[[tool.streamlit.component.components]]
name = "data_grid"
asset_dir = "data_grid/frontend/build"
